In [189]:
import numpy as np
import pandas as pd

In [190]:
df = pd.read_csv('StudentsPerformance.csv')

In [191]:
df.head()

gender     race parental_level_of_education         lunch  \
0  female  group B           bachelor's degree      standard   
1  female  group C                some college      standard   
2  female  group B             master's degree      standard   
3    male  group A          associate's degree  free/reduced   
4    male  group C                some college      standard   

   hrs_study_before_exam test_preparation_course  total_marks  
0                      6                    none          218  
1                      8               completed          247  
2                      9                    none          278  
3                      8                    none          278  
4                      4                    none          148

In [192]:
y = df['total_marks']

In [193]:
y = y.values

In [194]:
X = df[['gender', 'test_preparation_course', 'hrs_study_before_exam']]

In [195]:
X.shape

(299, 3)

In [196]:
X = X.values

In [197]:
from sklearn.preprocessing import OneHotEncoder

In [198]:
one_hot_encoder = OneHotEncoder()

Encoding gender

In [199]:
gender = df['gender']

In [200]:
gender = gender.values

In [201]:
gender = gender.reshape(-1, 1)

In [202]:
gender_dummy = one_hot_encoder.fit_transform(gender)

In [203]:
gender_final = gender_dummy.toarray()

In [204]:
gender_final = gender_final[:, 1]

In [205]:
gender_final = gender_final.reshape(-1, 1)

In [206]:
X = X[:, 1:3]

In [207]:
X = np.hstack((X, gender_final))

Encoding Parenetal Level Of Education

In [154]:
# ple = df['parental_level_of_education']

In [155]:
# ple = ple.values

In [156]:
# ple = ple.reshape(-1, 1)

In [157]:
# ple_dummy = one_hot_encoder.fit_transform(ple)

In [158]:
# ple_final = ple_dummy.toarray()

In [159]:
# ple_final = ple_final[:, 0:5]

In [160]:
# X = X[:, 1:3]

In [161]:
# X = np.hstack((X, ple_final))

Encoding Test Preparation Course

In [208]:
tpc = df['test_preparation_course']

In [209]:
tpc = tpc.values

In [210]:
tpc = tpc.reshape(-1, 1)

In [211]:
tpc_dummy = one_hot_encoder.fit_transform(tpc)

In [212]:
tpc_final = tpc_dummy.toarray()

In [213]:
tpc_final = tpc_final[:, 0:1]

In [216]:
X = X[:, 1:3]

In [217]:
X = np.hstack((X, tpc_final))

In [218]:
X.shape

(299, 3)

In [219]:
# X['hrs_study_before_exam', 'gender', 'test_preparation_course']
X

array([[6, 0.0, 0.0],
       [8, 0.0, 1.0],
       [9, 0.0, 0.0],
       [8, 1.0, 0.0],
       [4, 1.0, 0.0],
       [5, 0.0, 0.0],
       [6, 0.0, 1.0],
       [4, 1.0, 0.0],
       [6, 1.0, 1.0],
       [5, 0.0, 0.0],
       [5, 1.0, 0.0],
       [4, 1.0, 0.0],
       [7, 0.0, 0.0],
       [7, 1.0, 1.0],
       [6, 0.0, 0.0],
       [7, 0.0, 0.0],
       [7, 1.0, 0.0],
       [3, 0.0, 0.0],
       [4, 1.0, 1.0],
       [5, 0.0, 0.0],
       [5, 1.0, 0.0],
       [5, 0.0, 1.0],
       [3, 1.0, 0.0],
       [6, 0.0, 0.0],
       [8, 1.0, 1.0],
       [7, 1.0, 0.0],
       [5, 1.0, 0.0],
       [5, 0.0, 0.0],
       [7, 1.0, 0.0],
       [6, 0.0, 0.0],
       [6, 0.0, 0.0],
       [5, 0.0, 0.0],
       [5, 0.0, 0.0],
       [3, 1.0, 0.0],
       [9, 1.0, 0.0],
       [8, 1.0, 1.0],
       [8, 0.0, 0.0],
       [5, 0.0, 0.0],
       [7, 0.0, 1.0],
       [6, 1.0, 0.0],
       [5, 1.0, 0.0],
       [7, 0.0, 0.0],
       [5, 0.0, 0.0],
       [7, 1.0, 1.0],
       [5, 0.0, 0.0],
       [5,

Train the model

In [220]:
from sklearn.linear_model import LinearRegression

In [221]:
model = LinearRegression()

In [222]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [223]:
model.coef_

array([22.18808977, -6.21887527,  6.59371327])

Predicting using model

In [235]:
model.predict([[10, 1, 1]])

array([287.62112783])